name: Build Docker Image And Push

on:
  push:
    branches: [master]

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          image: noelimmi/ytdlazure
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
